### ISSUE TITLE
Missing documentation for SDK error codes

### ISSUE THREAD

**Issue by 7-plus-t** [idnow/de.idnow.ios.sdk.spm#22]
Version: 5.0.1
Type: With NFC

The following error codes are not documented in https://github.com/idnow/de.idnow.ios.sdk.spm#sdk-error-codes
- E10
- E120
- E121
- EUnreachable

**Comment by deryck-tomiuc-idnow** [comment]
Hello @7-plus-t,
Thank you bringing this up to our attention. We will be updating the documentation soon.
Till then, 
E10 - is a general type of error, which is currently in discussion to be more specific from case to case.
E120 - is a parsing error. because we are doing multiple HTTP requests, if the response is malformed, this error will be thrown.
E121 - Is a server type error which can occur when we are unable to fetch some resources from the customer config.
EUnreachable - is an error we are throwing when the SDK is initializing, but no network connection has been detected.
If I can help you in any way with other questions, please let me know.
Regards. Deryck

**Comment by juliancadi** [comment]
@deryck-tomiuc-idnow, what's the meaning of getting `FINISHED` in `IDNowSDK.IdentResult.type` but `E10` in `IDNowSDK.IdentResult.statusCode` at the same time? 

Should `E10` general error be ignored when `IDNowSDK.IdentResult.type` is **NOT** `ERROR` type? Or is there currently an inconsistency/bug in the SDK?

**Comment by deryck-tomiuc-idnow** [comment]
Hello @juliancadi, the errorCode should only be taken into consideration if the result type is error. The current behavior is known and we are addressing it in a future release.

**Comment by 7-plus-t** [comment]
@deryck-tomiuc-idnow Thanks for the explanations :) 

I will leave this issue open until it's fixed in the `README.md`

**Comment by deryck-tomiuc-idnow** [comment]
Hello @7-plus-t, let me know if the information from the Readme is sufficient. Regards.

**Comment by 7-plus-t** [comment]
Hi @deryck-tomiuc-idnow, looks fine to me. Thanks for completing the list.
